name: Shell Commands - On Push

on: [push]

jobs: 
  run-shell-command: # Key/Name of the job
    runs-on: ubuntu-latest # Virtual machine to run on 
    steps: # Each step the job
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: | 
          node -v
          npm -v
      - name: python command 
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  run-window-command: 
    runs-on: windows-latest 
    needs: ['run-shell-command'] # What the job relies on to avoid running in parallel
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash